# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-stretch-browsers@sha256:946141c7d39985c09172a2f168faf16bd8982c5a925c447b24bcc9e170ea55cf
      # - image: circleci/mongo:3.4.4
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          name: Restore NPM Package Cache
          keys:
            - npm-packages-{{ .Branch }}-{{ checksum "package.json" }}
            - npm-packages-{{ .Branch }}
            - npm-packages-master
            - npm-packages-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          name: Save NPM Package Cache
          key: npm-packages-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules/
      - run:
          name: Test
          command: npm test
      - run:
          name: Code coverage report
          command: |
            sudo npm install -g codeclimate-test-reporter codecov
            rm -rf .nyc_output
            mkdir -p .nyc_output
            grep '^:cov ' test.log | bash -c 'while read COV HASH OBJECT; do echo $OBJECT > .nyc_output/$HASH.json; done'
            npx nyc report --reporter=text-lcov > coverage.lcov
            codeclimate-test-reporter < coverage.lcov
            codecov
      - run:
          name: Build
          command: npm build
      - deploy:
          name: Install AWS tool
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              sudo apt-get update && sudo apt-get install -qq -y python-pip libpython-dev
              curl -O https://bootstrap.pypa.io/get-pip.py && sudo python get-pip.py
              sudo pip install -q awscli --upgrade
            fi
      - deploy:
          name: Deploy Master to S3
          working_directory: ~/repo
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              aws s3 sync dist/ s3://wrte.cloud/ --delete
            fi
